import pathlib

import click

TEMPLATE = """\
# ForceBalance input file generated by MakeInputFile.py
# The octothorpe '#' is a comment symbol
# Note: If the specified value is 'None' then the option will truly be set to None - not the string 'None'
# Note: 'Section' option types are more complicated and may require you to read the documentation
# Note: Boolean option types require no value, the key being present implies 'True'

$options
# (string) Directory containing force fields, relative to project directory
ffdir forcefield

# (string) Type of the penalty, L2 or L1 in the optimizer
penalty_type L2

# (allcap) The job type, defaults to a single-point evaluation of objective function
jobtype optimize

# (list) The names of force fields, corresponding to directory forcefields/file_name.(itp|gen)
forcefield force-field.offxml

# (int) Maximum number of steps in an optimization
maxstep 100

# (float) Convergence criterion of step size (just needs to fall below this threshold)
convergence_step 0.0001

# (float) Convergence criterion of objective function (in MainOptimizer this is the stdev of x2 over 10 steps)
convergence_objective 0.0001

# (float) Convergence criterion of gradient norm
convergence_gradient 0.0001

# The number of convergence criteria that must be met for main optimizer to converge
criteria 3

# (float) Minimum eigenvalue for applying steepest descent correction in the MainOptimizer
eig_lowerbound 0.01

# (float) Step size for finite difference derivatives in many functions (get_(G/H) in fitsim, FDCheckG)
finite_difference_h 0.001

# (float) Factor for multiplicative penalty function in objective function
penalty_additive 1.0

trust0 0.25
mintrust 0.05
error_tolerance 1.0
adaptive_factor 0.2
adaptive_damping 1.0
normalize_weights no
print_hessian

# any extras are added here like print hessian
wq_port  {port}
asynchronous  True
search_tolerance  0.1

# Charge constraints are taken care of using "evals".
constrain_charge false

priors
   vdW/Atom/epsilon :  0.1
   vdw/Atom/rmin_half :  1.0
/priors

$end

"""

TARGET_TEMPLATE = """\
$target
name {name}
type Interaction_SMIRNOFF
weight 1.0
mol2 fragment1.mol2 fragment2.mol2
fragment1 {fragment1}
fragment2 {fragment2}

remote 1
writelevel 1
$end

"""


def get_target_text(
    directory: str,
):
    from openff.toolkit.topology import Molecule

    directory = pathlib.Path(directory)
    name = directory.stem
    mol1 = Molecule.from_file(
        str(directory / "fragment1.mol2"),
        "MOL2"
    )
    mol2 = Molecule.from_file(
        str(directory / "fragment2.mol2"),
        "MOL2"
    )
    n_atoms1 = mol1.n_atoms
    n_atoms2 = mol2.n_atoms
    fragment1 = f"1-{n_atoms1}"
    fragment2 = f"{n_atoms1 + 1}-{n_atoms1 + n_atoms2}"
    return TARGET_TEMPLATE.format(
        name=name,
        fragment1=fragment1,
        fragment2=fragment2,
    )


@click.command()
@click.option(
    "--forcefield",
    "input_forcefield",
    type=str,
    help="Path to the input force field.",
)
@click.option(
    "--input",
    "input_directory",
    type=click.Path(exists=True, file_okay=False, dir_okay=True),
    help="Path to the input directory.",
)
@click.option(
    "--output",
    "output_directory",
    type=click.Path(exists=False, file_okay=False, dir_okay=True),
    help="Path to the output directory.",
)
@click.option(
    "--port",
    type=int,
    help="Port number for the queue.",
    default=57123,
)
def main(
    input_directory: str,
    input_forcefield: str,
    output_directory: str,
    port: int,
):
    from openff.toolkit.typing.engines.smirnoff import ForceField
    import numpy as np

    output_directory = pathlib.Path(output_directory)
    output_directory.mkdir(exist_ok=True, parents=True)

    # edit force field
    ff = ForceField(input_forcefield)
    vdw_handler = ff.get_parameter_handler("vdW")
    for parameter in vdw_handler.parameters:
        if "tip3p" in parameter.id:
            continue

        epsilon = parameter.epsilon
        epsilon_unit = epsilon.unit
        epsilon_log = np.log10(epsilon.value_in_unit(epsilon_unit))

        parameter.add_cosmetic_attribute("epsilon_log", epsilon_log * epsilon_unit)
        eval_cmd = f"epsilon=10 ** PRM['vdW/Atom/epsilon_log/{parameter.smirks}']"
        parameter.add_cosmetic_attribute("parameter_eval", eval_cmd)
        parameter.add_cosmetic_attribute("parameterize", "epsilon_log,rmin_half")

    forcefield_file = output_directory / "forcefield" / "force-field.offxml"
    forcefield_file.parent.mkdir(exist_ok=True, parents=True)
    ff.to_file(str(forcefield_file))
    print(f"Force field written to {forcefield_file}")

    input_directory = pathlib.Path(input_directory)
    target_directories = sorted(input_directory.glob("interaction-energy-*"))
    sections = [TEMPLATE.format(port=port)]
    for target_directory in target_directories:
        sections.append(get_target_text(target_directory))
    
    text = "\n".join(sections)
    output_file = pathlib.Path(output_directory) / "optimize.in"
    output_file.write_text(text)
    print(f"Input file written to {output_file}")



if __name__ == "__main__":
    main()
