name: evaluator-vsites-hfes-0.3
channels:
  - openeye
  - simonboothroyd
  - conda-forge
dependencies:
  - python ==3.9.18
  - pip
  # fits and properties
  - openff-toolkit ==0.10.7 
  - openff-units ==0.1.6
  - openff-recharge ==0.0.1
  - openff-qcsubmit ==0.3.2
  - openff-bespokefit ==0.1.1
  - nonbonded

  - openmm ==7.7.0
  - openmmtools ==0.21.5

  - openeye-toolkits ==2022.1.1
  - pymbar ==3.0.5
  - yank ==0.25.2

  # evaluator dependencies
  - packmol
  - pyyaml
  - paprika
  - dataclasses
  - cmiles
  - networkx
  - smirnoff99frosst

  # compatibility
  - cython <3
  - pint ==0.17

  # other
  - tqdm
  - click
  - mdanalysis
  - seaborn
  - pandas
  - dask
  - dask-jobqueue 
  - pip:
      - amberutils==21.0
      - edgembar==0.2
      - mmpbsa-py==16.0
      - packmol-memgen==2023.2.24
      - pdb4amber==22.0
      - pymsmt==22.0
      - pytraj==2.0.6
      - sander==22.0
      - git+https://github.com/lilyminium/openff-evaluator.git@dd5fe85
      - git+https://github.com/lilyminium/mdtraj.git@14af22e
